workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd flutter_app
          flutter packages pub get
      
      - name: Build AAB
        script: |
          cd flutter_app
          flutter build appbundle --release --build-number=$PROJECT_BUILD_NUMBER
          
    artifacts:
      - flutter_app/build/app/outputs/**/*.aab
      - flutter_app/build/app/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - your-email@example.com