workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx4g"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g"
      flutter: stable
    scripts:
      - name: Clean and force dependency update
        script: |
          cd flutter_app
          rm -f pubspec.lock
          flutter clean
          flutter pub get --enforce-lockfile=false

      - name: Build AAB
        script: |
          cd flutter_app
          flutter build appbundle --debug --build-number=$PROJECT_BUILD_NUMBER

    artifacts:
      - flutter_app/build/**/outputs/**/*.aab
      - flutter_app/build/**/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com