name: agile_project_app
description: A Flutter app for agile project management

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Network & API (Updated versions)
  dio: ^5.8.0
  http: ^1.2.1
  
  # Storage (Updated versions)  
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.4
  
  # State Management
  provider: ^6.1.2
  
  # Navigation (Updated version)
  go_router: ^14.2.7
  
  # Serialization
  json_annotation: ^4.9.0
  
  # Internationalization (Updated)
  intl: ^0.20.2
  
  # Notifications (Updated)
  flutter_local_notifications: ^17.2.2
  
  # WebSocket (Updated)
  web_socket_channel: ^3.0.3
  
  # Media & Files (Updated)
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # Connectivity & Permissions (CRITICAL UPDATES)
  connectivity_plus: ^6.1.5
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/