name: agile_project_app
description: A Flutter app for agile project management

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^4.2.1
  provider: ^6.1.5
  go_router: ^13.2.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.1
  web_socket_channel: ^2.4.0
  image_picker: ^1.0.8
  cached_network_image: ^3.3.1
  connectivity_plus: ^2.3.8
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/