name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
      - run: |
          cd flutter_app
          flutter build apk --release --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: flutter_app/build/app/outputs/apk/release/